const tracing = require('opentracing');
const constants = require('./constants');

module.exports = Object.assign({
  AUTH0_TENANT: constants.TAG_AUTH0_TENANT,
  AUTH0_ENVIRONMENT: constants.TAG_AUTH0_ENVIRONMENT,
  AUTH0_REGION: constants.TAG_AUTH0_REGION,
  AUTH0_CHANNEL: constants.TAG_AUTH0_CHANNEL,
  AUTH0_HOSTNAME: constants.TAG_AUTH0_HOSTNAME,
  AUTH0_PURPOSE: constants.TAG_AUTH0_PURPOSE,
  AUTH0_REQUEST_ID: constants.TAG_AUTH0_REQUEST_ID,
  AUTH0_WORKER_QUEUE: constants.TAG_AUTH0_WORKER_QUEUE,
  AUTH0_WORKER_STRATEGY: constants.TAG_AUTH0_WORKER_STRATEGY,
  AUTH0_WORKER_REQUEUE: constants.TAG_AUTH0_WORKER_REQUEUE,
  AUTH0_JOB_ID: constants.TAG_AUTH0_JOB_ID,
  AUTH0_JOB_TYPE: constants.TAG_AUTH0_JOB_TYPE,
  AUTH0_CLIENT_ID: constants.TAG_AUTH0_CLIENT_ID,
  AUTH0_CONNECTION_NAME: constants.TAG_AUTH0_CONNECTION_NAME,
  AUTH0_IS_RETRY: constants.TAG_AUTH0_IS_RETRY,
  AUTH0_RETRIES: constants.TAG_AUTH0_RETRIES,

  HTTP_PATH: 'http.path',
}, tracing.Tags);
